version: 2.1
orbs:
  node: circleci/node@5
  docker: circleci/docker@1.4.0

jobs:
  build-and-push:
    environment:
      DOCKER_IMAGE: image/ci_cd
      DOCKER_TAG: latest
    executor: docker/docker
    steps:
      - setup_remote_docker
      - checkout
      - docker/check:
          docker-username: DOCKER_USER
          docker-password: DOCKER_PASSWORD
      - docker/build:
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - docker/push:
          digest-path: /tmp/digest.txt
          image: $DOCKER_IMAGE
          tag: $DOCKER_TAG
      - run:
          command: |
            echo "Digest is: $(</tmp/digest.txt)"

workflows:
  test-build-deploy: # đây chỉ là tên của workflow, không quan trọng
    jobs: # đây là danh sách các job
      - node/test
      - build-and-push:
          # 1. Chỉ build trên nhánh master
          # 2. Chỉ build khi job node/test đã thành công
          requires:
            - node/test
          filters:
            branches:
              only:
                - master

# Từ dòng 20 trở lại là các lệnh chuẩn bị (prepare commands)
# Từ dòng 21 trở xuống là chạy các lệnh đã chuẩn bị ở trên
# build-and-push là tên của job chuẩn bị ở trên
